cities:
  Augsburg:
    - https://t.me/augsburghilftukraine
  Baden-Württemberg:
    - https://t.me/+n8doQy7ubEBmZGE6
  Bayern:
    - https://t.me/+95kDURdyTlE2YjFi
  Belgium:
    - https://t.me/refugeesinBelgium
  Berlin:
    - https://t.me/+pY4AEUY_0jZhMzQ0
    - https://t.me/ukrainehelpberlin
    - https://t.me/+IteYrWFkvcs5Njli
    - https://t.me/accomodationsunday
  Bielefeld:
    - https://t.me/bielefeldhelps
  Bochum:
    - https://t.me/ukraine_bochum_support
  Brandenburg:
    - https://t.me/+2aZQNYb1hns3Mzli
  Braunschweig:
    - https://t.me/BS_UA_HELP
    - https://t.me/UkrHelp_Braunschweig
  Bremen:
    - https://t.me/ukrainebremen
    - https://t.me/suport_ukraine_in_bremen
    - https://t.me/Bremenhelpsukraine
    - https://t.me/SolidarityUkraineBremen
    - http://bremenwithukraine.com/
    - https://t.me/+XRsorLrY4iRjYTgy
  Chemnitz:
    - https://t.me/pomosh_Germany_Chemnitz_Ukraine
  Dortmund:
    - https://t.me/ukraine_dortmund
  Dresden:
    - https://t.me/+djV5nXL6pWdlYmQ6
  Duisburg:
    - https://t.me/duisburgukraine
  Düsseldorf:
    - https://t.me/duesseldorf_ukraina
  Essen:
    - https://t.me/ukr_de_essen
  Erfurt:
    - https://t.me/thuringia_stands_with_ukraine
  Frankfurt am Main:
    - https://t.me/+BcQ_210Ex4cwYjEy
  Freiburg:
    - https://t.me/freiburghilft
  Hamburg:
    - https://t.me/hamburg_hilft
    - https://t.me/+5XuTo4a1gmw3YTcy
  Hannover:
    - https://t.me/+m5HzIyVixn5iZGQy
    - https://t.me/+Bm1Uk3JJ4FJkMDFi
  Heilbronn:
    - https://t.me/+zc9HnLCyckMzMGRi
  Hessen:
    - https://t.me/+HTYW-_jDZVtkZDJi
  Jena:
    - https://t.me/thuringia_stands_with_ukraine
  Karlsruhe:
    - https://t.me/+AONMSwz2i405MDQ6
    - https://t.me/ukraine_karlsruhe
    - https://t.me/ua_ka_help
    - https://t.me/karlsruhespendenfuerukraine
  Kassel:
    - https://t.me/KasselUkrainehilfen
    - https://t.me/KSHELPUKRIANE
  Köln:
    - https://t.me/cologne_help
  Leipzig:
    - https://t.me/ukrainerinleipzig
    - https://t.me/accomodation_leipzig_ukraine
    - https://t.me/ukrainerinleipzigACCOMODATION
  Magdeburg:
    - https://t.me/magdeburg_ukraine
  Mainz:
    - https://t.me/ukraine_helfen_mainz
  Mannheim:
    - https://t.me/UkrHlfMA
  Mecklenburg-Vorpommern:
    - https://t.me/+ACMWRk-ONEllMzEy
  München:
    - https://t.me/helpUkrainetowin
  Nordrhein-Westfalen:
    - https://t.me/+iVakIX2oQK1jYmFi
    - https://t.me/Help_Ukraine_NRW
  Niedersachsen:
    - https://t.me/+sySBMibwdz9hMmIy
  Nürnberg:
    - https://t.me/help_in_Nuremberg_UA
  Paris:
    - https://t.me/+KUk3d_a3w7dkYWI0
  Potsdam:
    - https://t.me/potsdamhelpsukrainians
    - https://t.me/+U076iU76y5I0OTli
  Rheinland-Pfalz:
    - https://t.me/ukrainerheinlandpfalz
    - https://t.me/+G1BeTeo1-Qc4MDUy
  Rostock:
    - https://t.me/HilfstransporteRostockUkraine
  Saarland:
    - https://t.me/ukrainesaarland
    - https://t.me/+2L_IOBE5fspmOWM6
  Sachsen:
    - https://t.me/+evMXd6nO5T1mMDIy
  Sachsen-Anhalt:
    - https://t.me/+IWXBYfN9765mODZi
  Schleswig-Holstein:
    - https://t.me/+IhWtHU4b5HsyNGIy
  Schwerin:
    - https://t.me/+ACMWRk-ONEllMzEy
  Stuttgart:
    - https://t.me/helpforukraine22
  Thüringen:
    - https://t.me/thuringia_stands_with_ukraine
    - https://t.me/th_helps_ukraine
    - https://t.me/+9R0NgYYt91kwNmUy
  Vienna:
    - https://t.me/warhelpeuplaces
  Weimar:
    - https://t.me/thuringia_stands_with_ukraine
  Wuppertal:
    - https://t.me/ukrainehilfewuppertal
  Zurich:
    - https://t.me/zh_helps_ukraine

countries:
  Ukraine:
    - https://t.me/refugeesinUkraine
  Austria:
    - https://t.me/refugeesinAustria
  France:
    - https://t.me/refugeesinFrance
  Germany:
    - https://t.me/refugees_in_Germany
  Italy:
    - https://t.me/dodomu_italia_ucraina
  Netherlands:
    - https://t.me/help_ua_nl_bot
    - https://infohelpua.com/
    - https://m.facebook.com/OekrainersInNederland/
    - https://www.amsterdam.nl/en/refugees/amsterdam-supports-ukraine/
  Poland:
    - https://t.me/refugeesinPoland
  Spain:
    - https://t.me/HelpUkraineEspana
  Sweden:
    - https://t.me/refugeesinSweden
  Switzerland:
    - https://t.me/refugeesinSwitzerland
  Австрия:
    - https://t.me/refugeesinAustria
  Бельгия:
    - https://t.me/refugeesinBelgium
  Германия:
    - https://t.me/refugees_in_Germany
  Испания:
    - https://t.me/HelpUkraineEspana
  Италия:
    - https://t.me/dodomu_italia_ucraina
  Нидерланды:
    - https://t.me/help_ua_nl_bot
    - https://infohelpua.com/
    - https://m.facebook.com/OekrainersInNederland/
    - https://www.amsterdam.nl/en/refugees/amsterdam-supports-ukraine/
  Польша:
    - https://t.me/refugeesinPoland
  Украина:
    - https://t.me/refugeesinUkraine
  Франция:
    - https://t.me/refugeesinFrance
  Швейцария:
    - https://t.me/refugeesinSwitzerland
  Швеция:
    - https://t.me/refugeesinSweden

evacuation:
  Эвакуация из Украины:
    - https://www.ukrainenow.org/refuge
  Чат по эвакуации:
    - https://t.me/perevezite

evacuation_cities:
  Белая Церковь:
    - https://t.me/+A4vJpMa-iqY3NzJi
  Бердичів:
    - https://t.me/+g1vCeKfEve5lNTM6
  Винница:
    - https://t.me/+LeEGgnB7RwcxYWI0
  Днепр:
    - https://t.me/+LpQlRQvCas1jNmI0
  Донецкая область (Покровский район):
    - https://t.me/pokrovsk_don
  Житомир:
    - https://t.me/+QD2EEIJqf_xhYjQ8
  Запорожье:
    - https://t.me/+ynRJn88RxgswYmU0
  Луганская область:
    - https://t.me/luhanskevaquation
  Иваново-франковск:
    - https://t.me/+nzeP_stFB3I1MjU0
  Киев:
    - https://t.me/+68JG-qKNvm9kNjZi
  Кировоград:
    - https://t.me/+z5TkEVbqiatkOGE0
  Кривий Ріг:
    - https://t.me/+SguKJv2dQGRkM2Zk
  Луцк:
    - https://t.me/+R49w2c4seXw5MzJk
  Львов:
    - https://t.me/+UNdwIrUYEBgwOWE8
  Николаев:
    - https://t.me/+isy_Cw5MrptmZjlk
  Одесса:
    - https://t.me/+Dg2rSrkmuN03NGFk
  Павлоград:
    - https://t.me/pavlogradevak
  Полтава:
    - https://t.me/+AGqMw2Sl4ABjMmI0
  Познань:
    - https://t.me/+XiWfyDBY7WExNDI0
  Ровно:
    - https://t.me/+hwq625pYpfUzOWI8
  Сумы:
    - https://t.me/+-oVnhuNnwpU1ZWVk
  Тернопіль:
    - https://t.me/+HK4nfvMpAeM1MWZk
  ужгород:
    - https://t.me/+5WlQQHIKJ4NjMGNk
  Харьков:
    - https://t.me/+vSsvEw-pfNA4NDdi
  Хмельницкий:
    - https://t.me/+qORus3EoBnEzZmNk
  Черкассы:
    - https://t.me/EvacuationCherkasy
  Черновцы:
    - https://t.me/evacuationChernovtsy
  Чернiгiв:
    - https://t.me/+i1Np0FJLhs4zMzli
taxis:
  - "taxi phone: +49 30 202020"
medical:
  General:
    - "Бесплатное медицинское обеспечение"
    - https://www.berlin.de/ukraine/ru/pribytie/okasanie-medizinskoj/
    - https://handbookgermany.de/de/ukraine-info/ru/medizinische-versorgung.html
    - http://www.gesundheit-ein-menschenrecht.de/kontaktstellen
    - https://www.kvberlin.de/fuer-patienten/ukraine?fbclid=IwAR3OV_-vw6rw14wOAKcpEK5HucFTia3Ugt0sy1KipI9qsjB56Uochqm3PSo
    - https://www.malteser.de/menschen-ohne-krankenversicherung.html
    - https://www.berlin-aidshilfe.de/
  Pregnant:
    - https://chat.whatsapp.com/GPDPtkjiMlf1HnSIttlKtS
    - https://www.berlin.de/ba-friedrichshain-kreuzberg/politik-und-verwaltung/aemter/gesundheitsamt/zentrum-fuer-sexuelle-gesundheit-und-familienplanung/russ_flyer-zentrum-fk-15x15.pdf
  Psychological:
    - https://www.imja.online/charity
  Gynecologist:
    - "Гинеколог:\nHerr Matthias Rödel (Speaks Russian) \n Hermannstr.147 \n 12051 Berlin \n 030/6222097"
dentist:
  Врачи:
    - "Зубной:\nDavid Stolyar (Speaks Russian) \nWindscheidstr. 11 \n10627 Berlin-Charlottenburg \n+49 (0)30 - 32 70 17-18"
  Инфо:
    - "В экстренном случае, зубные врачи могут предоставить бесплатную стоматологическую помошь. При себе необходимо иметь украиский паспорт. \n\n https://news.kzv-berlin.de/detail/nachricht/zahnmedizinische-versorgung-von-fluechtlingen-aus-der-ukraine"
jobs:
  Каналы:
    - https://t.me/jobforukrainians
    - https://t.me/jobsforukraine
    - https://t.me/euvacancies_for_evacuated
  Сайты:
    - https://www.uatalents.com
    - https://hireforukraine.org/
    - https://jobsforukraine.net
    - https://www.jobaidukraine.com/
    - https://www.jobs4ukraine.eu/91ce6995f87d40c1816ae05a7686a9c7