cities:
  Altmark:
    - https://t.me/+slxkkb7eY9w0Y2Qy
  Augsburg:
    - https://t.me/augsburghilftukraine
  Baden-Württemberg:
    - https://t.me/+n8doQy7ubEBmZGE6
  Bayern:
    - https://t.me/+95kDURdyTlE2YjFi
  Berlin:
    - https://t.me/+pY4AEUY_0jZhMzQ0
    - https://t.me/ukrainehelpberlin
    - https://t.me/+IteYrWFkvcs5Njli
    - https://t.me/accomodationsunday
  Bielefeld:
    - https://t.me/bielefeldhelps
  Bochum:
    - https://t.me/ukraine_bochum_support
  Brandenburg:
    - https://t.me/+2aZQNYb1hns3Mzli
  Braunschweig:
    - https://t.me/BS_UA_HELP
    - https://t.me/UkrHelp_Braunschweig
  Bremen:
    - https://t.me/ukrainebremen
    - https://t.me/suport_ukraine_in_bremen
    - https://t.me/Bremenhelpsukraine
    - https://t.me/SolidarityUkraineBremen
    - http://bremenwithukraine.com/
    - https://t.me/+XRsorLrY4iRjYTgy
  Chemnitz:
    - https://t.me/pomosh_Germany_Chemnitz_Ukraine
  Dortmund:
    - https://t.me/ukraine_dortmund
  Dresden:
    - https://t.me/+djV5nXL6pWdlYmQ6
  Duisburg:
    - https://t.me/duisburgukraine
  Düsseldorf:
    - https://t.me/duesseldorf_ukraina
  Essen:
    - https://t.me/ukr_de_essen
  Erfurt:
    - https://t.me/thuringia_stands_with_ukraine
  Frankfurt am Main:
    - https://t.me/+BcQ_210Ex4cwYjEy
  Freiburg:
    - https://t.me/freiburghilft
  Görlitz:
    - https://t.me/Goerlitz_helps_Ukraine
  Hamburg:
    - https://t.me/hamburg_hilft
    - https://t.me/+5XuTo4a1gmw3YTcy
  Hannover:
    - https://t.me/+m5HzIyVixn5iZGQy
    - https://t.me/+Bm1Uk3JJ4FJkMDFi
  Heilbronn:
    - https://t.me/+zc9HnLCyckMzMGRi
  Hessen:
    - https://t.me/+HTYW-_jDZVtkZDJi
  Jena:
    - https://t.me/thuringia_stands_with_ukraine
  Karlsruhe:
    - https://t.me/+AONMSwz2i405MDQ6
    - https://t.me/ukraine_karlsruhe
    - https://t.me/ua_ka_help
    - https://t.me/karlsruhespendenfuerukraine
  Kassel:
    - https://t.me/KasselUkrainehilfen
    - https://t.me/KSHELPUKRIANE
  Köln:
    - https://t.me/cologne_help
  Leipzig:
    - https://t.me/ukrainerinleipzig
    - https://t.me/accomodation_leipzig_ukraine
    - https://t.me/ukrainerinleipzigACCOMODATION
  Lüneburg:
    - https://t.me/+slxkkb7eY9w0Y2Qy
  Magdeburg:
    - https://t.me/magdeburg_ukraine
  Mainz:
    - https://t.me/ukraine_helfen_mainz
  Mannheim:
    - https://t.me/UkrHlfMA
  Mecklenburg-Vorpommern:
    - https://t.me/+ACMWRk-ONEllMzEy
  München:
    - https://t.me/helpUkrainetowin
  Nordrhein-Westfalen:
    - https://t.me/+iVakIX2oQK1jYmFi
    - https://t.me/Help_Ukraine_NRW
  Niedersachsen:
    - https://t.me/+sySBMibwdz9hMmIy
  Nürnberg:
    - https://t.me/help_in_Nuremberg_UA
  Paris:
    - https://t.me/+KUk3d_a3w7dkYWI0
  Potsdam:
    - https://t.me/potsdamhelpsukrainians
    - https://t.me/+U076iU76y5I0OTli
  Rheinland-Pfalz:
    - https://t.me/ukrainerheinlandpfalz
    - https://t.me/+G1BeTeo1-Qc4MDUy
  Rostock:
    - https://t.me/HilfstransporteRostockUkraine
  Saarland:
    - https://t.me/ukrainesaarland
    - https://t.me/+2L_IOBE5fspmOWM6
  Sachsen:
    - https://t.me/+evMXd6nO5T1mMDIy
  Sachsen-Anhalt:
    - https://t.me/+IWXBYfN9765mODZi
  Schleswig-Holstein:
    - https://t.me/+IhWtHU4b5HsyNGIy
  Schwerin:
    - https://t.me/+ACMWRk-ONEllMzEy
  Stuttgart:
    - https://t.me/helpforukraine22
  Thüringen:
    - https://t.me/thuringia_stands_with_ukraine
    - https://t.me/th_helps_ukraine
    - https://t.me/+9R0NgYYt91kwNmUy
  Uelzen:
    - https://t.me/+slxkkb7eY9w0Y2Qy
  Vienna:
    - https://t.me/warhelpeuplaces
  Wendland:
    - https://t.me/+slxkkb7eY9w0Y2Qy
  Weimar:
    - https://t.me/thuringia_stands_with_ukraine
  Wuppertal:
    - https://t.me/ukrainehilfewuppertal
  Zurich:
    - https://t.me/zh_helps_ukraine

countries:
  Ukraine:
    - https://t.me/refugeesinUkraine
  Austria:
    - https://t.me/refugeesinAustria
    - https://t.me/ukrainciwbelgii
  Belgium:
    - https://t.me/refugeesinBelgium
  Denmark:
    - https://t.me/refugeesinDenmark
  France:
    - https://t.me/refugeesinFrance
  Germany:
    - https://t.me/refugees_in_Germany
    - https://t.me/germanyhelpsukraine
    - https://t.me/ru_de_help
    - https://t.me/helpUkraine_Gemany
    - https://t.me/UKR_DE
  Hungary:
    - https://t.me/hungaryua
    - https://t.me/helpinhungary
    - https://t.me/HUvolunteerswithUA
    - https://help.unhcr.org/hungary/uk/
    - https://ukrainehelp.hu/
  Italy:
    - https://t.me/dodomu_italia_ucraina
  Latvia:
    - https://www.ukraine-latvia.com/uk
  Moldova:
    - https://t.me/moldovaukraina
    - https://ua-md-help.info/
    - https://dopomoga.gov.md/
  Netherlands:
    - https://t.me/help_ua_nl_bot
    - https://infohelpua.com/
    - https://m.facebook.com/OekrainersInNederland/
    - https://www.amsterdam.nl/en/refugees/amsterdam-supports-ukraine/
  Poland:
    - https://t.me/refugeesinPoland
    - https://ukrainesupport.net/uk/
    - https://help.unhcr.org/poland/uk/
  Portugal:
    - https://t.me/+j3_sMgK6QG8yMmVi
    - https://www.sef.pt/en/Pages/homepage.aspx
  Romania:
    - https://t.me/UkrainiansinRomania
    - https://www.facebook.com/groups/unitipentruucraina/
  Slovakia:
    - https://t.me/ukrajinci_na_slovensku
    - https://www.ukraineslovakia.sk/
  Slovenia:
    - https://www.facebook.com/groups/179196962897968/
  Spain:
    - https://t.me/HelpUkraineEspana
  Sweden:
    - https://t.me/refugeesinSweden
    - https://t.me/ukrainian_in_sweden
  Switzerland:
    - https://t.me/refugeesinSwitzerland
  Turkey:
    - https://t.me/+-MqndJ_hUQY2Yzdk
evacuation:
  Эвакуация из Украины:
    - https://www.ukrainenow.org/refuge
  Чат по эвакуации:
    - https://t.me/perevezite
evacuation_cities:
  Белая Церковь:
    - https://t.me/+A4vJpMa-iqY3NzJi
  Бердичів:
    - https://t.me/+g1vCeKfEve5lNTM6
  Винница:
    - https://t.me/+LeEGgnB7RwcxYWI0
  Днепр:
    - https://t.me/+LpQlRQvCas1jNmI0
  Донецкая область (Покровский район):
    - https://t.me/pokrovsk_don
  Житомир:
    - https://t.me/+QD2EEIJqf_xhYjQ8
  Запорожье:
    - https://t.me/+ynRJn88RxgswYmU0
  Луганская область:
    - https://t.me/luhanskevaquation
  Иваново-франковск:
    - https://t.me/+nzeP_stFB3I1MjU0
  Киев:
    - https://t.me/+68JG-qKNvm9kNjZi
  Кировоград:
    - https://t.me/+z5TkEVbqiatkOGE0
  Кривий Ріг:
    - https://t.me/+SguKJv2dQGRkM2Zk
  Луцк:
    - https://t.me/+R49w2c4seXw5MzJk
  Львов:
    - https://t.me/+UNdwIrUYEBgwOWE8
  Николаев:
    - https://t.me/+isy_Cw5MrptmZjlk
  Одесса:
    - https://t.me/+Dg2rSrkmuN03NGFk
  Павлоград:
    - https://t.me/pavlogradevak
  Полтава:
    - https://t.me/+AGqMw2Sl4ABjMmI0
  Познань:
    - https://t.me/+XiWfyDBY7WExNDI0
  Ровно:
    - https://t.me/+hwq625pYpfUzOWI8
  Сумы:
    - https://t.me/+-oVnhuNnwpU1ZWVk
  Тернопіль:
    - https://t.me/+HK4nfvMpAeM1MWZk
  ужгород:
    - https://t.me/+5WlQQHIKJ4NjMGNk
  Харьков:
    - https://t.me/+vSsvEw-pfNA4NDdi
  Хмельницкий:
    - https://t.me/+qORus3EoBnEzZmNk
  Черкассы:
    - https://t.me/EvacuationCherkasy
  Черновцы:
    - https://t.me/evacuationChernovtsy
  Чернiгiв:
    - https://t.me/+i1Np0FJLhs4zMzli
taxis:
  Центральное такси Берлина:
  - |-
    taxi phone: +49 30 202020
    https://www.taxi-berlin.de
medical:
  Бесплатное медицинское обслуживание:
    - https://www.berlin.de/ukraine/ru/pribytie/okasanie-medizinskoj/
    - https://handbookgermany.de/de/ukraine-info/ru/medizinische-versorgung.html
    - http://www.gesundheit-ein-menschenrecht.de/kontaktstellen
    - https://www.kvberlin.de/fuer-patienten/ukraine?fbclid=IwAR3OV_-vw6rw14wOAKcpEK5HucFTia3Ugt0sy1KipI9qsjB56Uochqm3PSo
    - https://www.malteser.de/menschen-ohne-krankenversicherung.html
    - https://www.berlin-aidshilfe.de/
    - https://www.kvberlin.de/fuer-patienten/ukraine
  Pregnant:
    - https://chat.whatsapp.com/GPDPtkjiMlf1HnSIttlKtS
    - https://www.berlin.de/ba-friedrichshain-kreuzberg/politik-und-verwaltung/aemter/gesundheitsamt/zentrum-fuer-sexuelle-gesundheit-und-familienplanung/russ_flyer-zentrum-fk-15x15.pdf
  Psychological:
    - https://www.imja.online/charity
    - https://krisenchat.de/ukraine
  Gynecologist:
    - |
      Гинеколог:
      Herr Matthias Rödel (Speaks Russian)
      Hermannstr.147
      12051 Berlin
      030/6222097
  Oncology:
    - https://medwatch.de/2022/03/11/информация-для-онкобольных-из-украин/
    - |-
      Клиники Германии, специализирующиеся на разных видах болезни:
      https://msp-ger.ru/oncology-in-germany/

dentist:
  Зубные врачи:
    - |
      David Stolyar (Speaks Russian)
      Windscheidstr. 11
      10627 Berlin-Charlottenburg
      +49 (0)30 - 32 70 17-18
  Информация:
    - |
      В экстренном случае зубные врачи могут предоставить бесплатную стоматологическую помошь. При себе необходимо иметь украинский паспорт.
      https://news.kzv-berlin.de/detail/nachricht/zahnmedizinische-versorgung-von-fluechtlingen-aus-der-ukraine
jobs:
  Каналы с рабочими предложениями:
    - https://t.me/jobforukrainians
    - https://t.me/jobsforukraine
    - https://t.me/euvacancies_for_evacuated
  Сайты для поиска работы:
    - https://www.uatalents.com
    - https://hireforukraine.org/
    - https://jobsforukraine.net
    - https://www.jobaidukraine.com/
    - https://www.jobs4ukraine.eu/91ce6995f87d40c1816ae05a7686a9c7
    - https://www.uatalents.com/
freestuff:
  Free clothes & food:
    - |
      https://gabenzaun.de/.#
    - |
      Центр Гуманитарной помощи беженцам из Украины
      Ansbacher Straße 30, 10789 Berlin
      Пн-Пт 10:00 - 18:00, Сб-Вс 10:00 - 16:00
      +49 152 08277408
    - |
      Check In Hotel
      Michael Brückner Str 1a, 12439 Berlin
      Opening times: Mo-Fr 15.00-20.00
    - |
      Holzmarkt 25
      Holzmarktstraße 25, 10243 Berlin
      Daily 14.00-20.00
  Miscellaneous free stuff:
    - https://www.ebay-kleinanzeigen.de/s-zu-verschenken/berlin/c192l3331
    - https://t.me/joinchat/CbD5mEn20K3k-gd-ckIXBw
    - https://www.facebook.com/groups/142044769198672
animals:
  Информация для владельцев животных:
    - https://t.me/+xM4h-4eFwpI4Yjgy
    - https://t.me/vetbel
    - https://www.facebook.com/groups/2082549321779139
volunteer:
  Donate your time in Berlin:
    - https://t.me/teamsuedkreuz
    - https://t.me/BerlinHbfArrival
    - https://t.me/arrivalcenter
    - http://volunteer-planner.org/
  Donate things in Berlin:
    - "Hbf: https://www.adiuto.org/berlin/hbf"
    - "Zob: https://www.adiuto.org/berlin/zob"
    - "Südkreuz: https://www.adiuto.org/berlin/suedkreuz"
    - "Ostbahnhof: https://www.adiuto.org/berlin/ostbahnhof"
    - "LAF/AKUZ: https://www.adiuto.org/berlin/akuz"
    - "Potsdam: https://www.adiuto.org/initiative/potsdam-welcome-team"
    - "Hangar 1, Columbiadamm 10, 12101 Berlin. Please email kontakt@hangar1.de"
deutsch:
  Изучение немецкого языка:
    - |
      Сейчас есть несколько вариантов, почитайте, пожалуйста, пост:
      https://t.me/berlinhelpsukrainians/60853
    - |
      Немецкий с Кристиной: https://t.me/+106hrEPfC-A1ZmIy
  Resources:
    - https://www.duolingo.com/
    - https://www.babbel.com/
travel:
  Buses:
    - https://corporate.flixbus.com/flixbus-supports-ukraine/
  Trains:
    - https://www.bahn.de/info/helpukraine
germany_domestic:
  Регистрация:
    - |
      Берлинский центр приёма беженцев практически переполнен.

      Имеет смысл ехать и регистрироваться в следующие пункты приёма беженцев:
      - Bremen / Бремен
      - Mecklenburg-Vorpommern / Мекленбург-Передняя Померания
      - Niedersachsen / Нижняя Саксония
      - Sachsen-Anhalt/ Саксония-Анхальт
      - Rheinland-Pfalz / Рейнланд-Пфальц
      - NRW / Северный Рейн-Вестфалия
  Bremen:
    - |
      Регистрация:

      Zentrale Aufnahmestelle für Asylbewerber & ausländische Flüchtlinge (ZASt)
      Alfred-Faust-Str. 15, 28277 Bremen
      Telefon: 0421 361 - 3148
      raymond.bohnenkamp@soziales.bremen.de
      zast@soziales.bremen.de
  Mecklenburg-Vorpommern:
    - |
      Регистрация:

      Amt für Migration und Flüchtlingsangelegenheiten
      Nostorfer Str. 1, 19258 Nostorf/Horst
      Telefon: 03855880, Fax: 038558856555
      amf-poststelle@laiv-mv.de
  Niedersachsen:
    - |
      Регистрация:

      Landesaufnahmebehörde Niedersachsen
      EAE Braunschweig\nBoeselagerstr. 4, 38108 Braunschweig
      Telefon:05313547-104 oder 109
      Carsten.Frambach@lab.niedersachsen.de
      Dagmar.Busse@lab.niedersachsen.de"
  Sachsen-Anhalt:
    - |
      Регистрация:

      Zentrale Anlaufstelle für Asylbewerber des Landes Sachsen-Anhalt
      Friedrich-List-Str. 1a 38820 Halberstadt
  Rheinland-Pfalz:
    - |
      Регистрация:

      Aufsichts- und Dienstleistungsdirektion
      Aufnahmeeinrichtung für Asylbegehrende
      Dasbachstraße 19, 54292 Trier
  Nordrhein-Westfalen:
    - |
      Регистрация:
      Landeserstaufnahmeeinrichtung (LEA)
      Gersteinring 50, 44791 Bochum 0293182 6600
humanitarian:
  Гуманитарная помощь:
    - |
      Центр гуманитарной помощи LaruHelps
      Ansbacher Str. 30, 10789 Berlin
      будни 10-20
      выходные 10-16
    - |
      Moabit hilft
      Turmstr. 21, Haus R, 10559 Berlin
      пн-пт 11-19
    - |
      Joachimsthaler Str. 25
      10719 Berlin
      чт, пт, сб 12-19
    - |
      Caritas Kleiderkammern Berlin
    - |
      склад Kidsmont
      Meeraner Str. 11E, 12681 Berlin
    - |
      склад
      Beusselstrasse 31, 10553 Berlin
      2. Hinterhof rechts (во втором дворе по правой стороне)
    - |
      VF Logistik
      Wallenroder Str. 7-9, 13435 Berlin
      пн-пт 8:30-16:30
    - |
      Ring Zentrum
      Frankfurter Allee 113-117, Berlin
    - |
      Kaminholz-Berlin
      Altonaer Str. 85, 13581 Berlin
    - |
      Hauptbahnhof (Главный вокзал)
    - |
      Razam + Haus der Statistik
      Otto-Braun str. 70-72, 10178, Berlin
      Haus B,
      пн-вскр 11-18
    - |-
      Berlin to Borders Charity Shop
      Holzmarkt Strasse 19, Berlin
      пн-вскр 14-20
      https://www.instagram.com/p/CbE0a-XJdJX/?utm_medium=copy_link
disabled:
  Help for disabled people:
  - https://www.familienratgeber.de/beratung-hilfe/weitere-hilfen/fluechtlinge-behinderung.php
  - https://www.interaktiv-berlin.de/
  - http://mina-berlin.eu/kontakt/
homesharing:
  Official resources for homesharing:
    - |-
       Люди, желающие предложить жилье беженцам, могут зарегистрироваться на сайте
       www.unterkunft-ukraine.de или
       https://airbnb.org/help-ukraine.
       BMI (Федеральное министерство внутренних дел и родины Германии кооперирует с этими платформами.
       Процесс, сопровождаемый организациями по оказанию помощи, обеспечивает безопасность для всех участвующих сторон.

       телеграм канал для поиска жилья в Берлине:
       https://t.me/BerlinHostUkranians

       If you're looking for a place to stay, please fill out one of this forms:
       - https://wunderflats.com/page/ukraine/tenants-in-need-ua
       - https://www.unterkunft-ukraine.de/request

       Or check here:
       - https://www.immobilienscout24.de/lp/hilfe-fuer-die-ukraine.html
       - https://www.shelter4ua.com
       - https://helppeopleleaveukraine.org
       - https://warmes-bett.de
       - https://icanhelp.host
       - https://www.host4ukraine.com
       - https://hospitality-helps.org
       - https://everybedhelps.com
